Fix rpm build error pth_mctx.c:480:2: error: #error "Unsupported Linux (g)libc version and/or platform"
This happens because there's a Linux kernel version check that
unfortunately only recognises 2.x versions, so it classifies a
3.x kernel as "braindead", which selects sjljlx and causes the
breakage.

The fix is to expand the kernel version regexp in aclocal.m4 to
also accept 3.x kernels

Link: https://bugzilla.redhat.com/attachment.cgi?id=591825

Change-Id: I0bf3356dda16d1d8e39811e92633699df15145ad
Signed-off-by: Mykola Tryshnivskyy <mykola.tryshnivskyy@globallogic.com>